# SPDX-FileCopyrightText: © 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# This file contains pre-commit checks.
# See https://github.com/j178/prek for details.

---
exclude: 'LICENSES/.*|tools/aspell\.en\.pws'

default_install_hook_types: [pre-commit, commit-msg]

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v6.0.0
   hooks:
    - id: check-added-large-files
      args: [--enforce-all]
    - id: check-case-conflict
    - id: check-illegal-windows-names
    - id: check-merge-conflict
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: forbid-submodules
    - id: requirements-txt-fixer
    - id: trailing-whitespace

 - repo: meta
   hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes

 # https://reuse.software/
 - repo: https://github.com/fsfe/reuse-tool
   rev: v6.2.0
   hooks:
    - id: reuse

 # https://docs.astral.sh/ruff/
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.15.20
   hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format

 - repo: https://github.com/crate-ci/typos
   rev: v1.47.2
   hooks:
    - id: typos
      stages: [pre-commit]
      args: []
    - id: typos
      stages: [commit-msg]
      args: []

 - repo: https://github.com/asottile/pyupgrade
   rev: v3.21.2
   hooks:
    - id: pyupgrade
      args: [--py313-plus]

 - repo: https://github.com/compilerla/conventional-pre-commit
   rev: v4.4.0
   hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args:
       [--strict,
        --verbose,
        --force-scope,
        --scopes,
        "10.5x,\
        ClematisM,\
        DoomDoctor,\
        FinalCustomDoom,\
        Gearbox,\
        Hint,\
        HitImpact,\
        LazyPoints,\
        LispOnZscript,\
        MD5,\
        Nomina,\
        PlainTranslator,\
        PreciseCrosshair,\
        PreviousWeapon,\
        SoundToScreen,\
        StringUtils,\
        TargetSpy,\
        Typist.pk3,\
        VmAbortReporter,\
        WarmReception,\
        libeye,\
        project",
        build, chore, docs, feat, fix, refactor, style, test]

 - repo: https://github.com/oxipng/oxipng
   rev: v10.1.1
   hooks:
    - id: oxipng
      args: [-o, '4', --alpha]

 - repo: https://github.com/rhysd/actionlint
   rev: v1.7.12
   hooks:
    - id: actionlint
      args: [-ignore, 'label ".+" is unknown']

 - repo: https://github.com/adrienverge/yamllint.git
   rev: v1.38.0
   hooks:
    - id: yamllint
      exclude: '.clang-format'
      args:
       [-d,
        '{extends: default, rules: {line-length: disable, truthy: disable}}',
        --strict]

 - repo: https://github.com/editorconfig-checker/editorconfig-checker
   rev: v3.8.0
   hooks:
    - id: editorconfig-checker
      exclude: 'modules/libeye.org|modules/MD5.org|tools/htmlize.el|tools/.*.wad'
      args: [-disable-indent-size]

 - repo: local
   hooks:
    - id: punctuation
      exclude: '.*\.gif|.*\.ogg|.*\.png|.*\.wad'
      name: punctuation
      language: pygrep
      # Forbidden characters:
      # - U+FFFD UTF-8 Unicode replacement character
      # - U+2018 LEFT SINGLE QUOTATION MARK
      # - U+2019 RIGHT SINGLE QUOTATION MARK
      # - U+201A SINGLE LOW-9 QUOTATION MARK
      # - U+201B SINGLE HIGH-REVERSED-9 QUOTATION MARK
      # - U+201C LEFT DOUBLE QUOTATION MARK
      # - U+201D RIGHT DOUBLE QUOTATION MARK
      # - U+201E DOUBLE LOW-9 QUOTATION MARK
      # - U+201F DOUBLE HIGH-REVERSED-9 QUOTATION MARK
      # - U+2E42 DOUBLE LOW-REVERSED-9 QUOTATION MARK
      entry: "\uFFFD|\u2018|\u2019|\u201A|\u201B|\u201C|\u201D|\u201E|\u201F|\u2E42"
