# SPDX-FileCopyrightText: © 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# This file contains pre-commit checks.
# See https://github.com/j178/prek for details.

exclude: 'LICENSES/.*|tools/aspell\.en\.pws'

default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-submodules
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes

# https://reuse.software/
-   repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
    -   id: reuse

# https://docs.astral.sh/ruff/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
    -   id: ruff-check
    -   id: ruff-format

-   repo: https://github.com/crate-ci/typos
    rev: v1.46.1
    hooks:
    -   id: typos
        stages: [pre-commit]
        args: []
    -   id: typos
        stages: [commit-msg]
        args: []

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py313-plus]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [--strict,
          --verbose,
          --force-scope,
          --scopes,
          '10.5x,DoomDoctor,FinalCustomDoom,Gearbox,Nomina,SoundToScreen,TargetSpy,Typist.pk3,WarmReception,project,Hint,LazyPoints,libeye,LispOnZscript,MD5,PlainTranslator,PreviousWeapon,StringUtils,VmAbortReporter',
          build, chore, docs, feat, fix, refactor, style, test
          ]
