# SPDX-FileCopyrightText: © 2026 Alexander Kromm (m8f) <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

StylesPath = build/styles
MinAlertLevel = warning

Packages =\
tools/vale-Microsoft-v0-15-0.zip,\
tools/vale-Openly-v0-4-6.zip,\
tools/vale-alex-v0-2-3.zip,\
tools/vale-neighbor-v2-2-0.zip,\
tools/vale-proselint-v0-3-4.zip,\
tools/vale-write-good-v0-4-1.zip

[*.{org,md}]

BasedOnStyles =\
Vale,\
vale-Microsoft-v0-15-0,\
vale-Openly-v0-4-6,\
vale-alex-v0-2-3,\
vale-neighbor-v2-2-0,\
vale-proselint-v0-3-4,\
vale-write-good-v0-4-1

Vale.Spelling = NO

vale-Microsoft-v0-15-0.FirstPerson = NO
vale-Microsoft-v0-15-0.HeadingAcronyms = NO
vale-Microsoft-v0-15-0.HeadingPunctuation = NO
vale-Microsoft-v0-15-0.Headings = error
vale-Microsoft-v0-15-0.Percentages = NO
vale-Microsoft-v0-15-0.Quotes = NO
vale-Microsoft-v0-15-0.Terms = NO
vale-Microsoft-v0-15-0.We = NO

vale-Openly-v0-4-6 = error
vale-Openly-v0-4-6.A11Y = NO
vale-Openly-v0-4-6.Clarity = NO
vale-Openly-v0-4-6.E-Prime = NO
vale-Openly-v0-4-6.FutureTense = NO
vale-Openly-v0-4-6.Readability = NO
vale-Openly-v0-4-6.Spelling = NO

vale-alex-v0-2-3.Ablist = NO
vale-alex-v0-2-3.ProfanityUnlikely = NO

vale-neighbor-v2-2-0.AbleistLanguage = NO
vale-neighbor-v2-2-0.AllCapsProse = NO
vale-neighbor-v2-2-0.ColonialAndViolentLanguage = NO
vale-neighbor-v2-2-0.DirectionalLanguage = NO

vale-proselint-v0-3-4.Annotations = NO

vale-write-good-v0-4-1.Passive = NO
vale-write-good-v0-4-1.TooWordy = NO
