# https://reuse.software/

version = 1

[[annotations]]
path = "media/10.5x/sprites/m8rda0.png"
SPDX-FileCopyrightText = "2023 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "config/aspell.en.pws"
SPDX-FileCopyrightText = "2025 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
