# https://reuse.software/

version = 1

[[annotations]]
path = "aspell.en.pws"
SPDX-FileCopyrightText = "2025 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "IgnoredGzdoomOutput.txt"
SPDX-FileCopyrightText = "2024 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
