# https://reuse.software/

version = 1

[[annotations]]
path = "aspell.en.pws"
SPDX-FileCopyrightText = "© 2025 Alexander Kromm (m8f) <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "IgnoredEngineOutput.txt"
SPDX-FileCopyrightText = "© 2024 Alexander Kromm (m8f) <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "miniwad.wad"
SPDX-FileCopyrightText = """\
Copyright © 2001-2018 Contributors to the Freedoom project. All rights reserved."""
SPDX-License-Identifier = "BSD-3-Clause"

# https://github.com/vale-cli/Microsoft
[[annotations]]
path = "vale-Microsoft-v0-15-0.zip"
SPDX-FileCopyrightText = "Copyright (c) 2018 - 2019 Joseph Kato"
SPDX-License-Identifier = "MIT"

# https://github.com/vale-cli/alex
[[annotations]]
path = "vale-alex-v0-2-3.zip"
SPDX-FileCopyrightText = "Copyright (c) 2020 errata.ai"
SPDX-License-Identifier = "MIT"

# https://github.com/a11yfred/neighbor
[[annotations]]
path = "vale-neighbor-v2-2-0.zip"
SPDX-FileCopyrightText = "Copyright (c) 2026 Mikey Ilagan"
SPDX-License-Identifier = "MIT"

# https://github.com/vale-cli/proselint
[[annotations]]
path = "vale-proselint-v0-3-4.zip"
SPDX-FileCopyrightText = "Copyright (c) 2019, errata.ai"
SPDX-License-Identifier = "BSD-3-Clause"

# https://github.com/vale-cli/write-good
[[annotations]]
path = "vale-write-good-v0-4-1.zip"
SPDX-FileCopyrightText = "Copyright (c) 2019 errata.ai"
SPDX-License-Identifier = "MIT"
