# Lines starting with # are comments, they are not exported to HTML.
# Some comments have special meaning, like "#+title:", "#+begin_src", "#+end_src".
#+title: Org Cheat Sheet

If you are reading this file on GitHub or Codeberg: not all Org features may be
supported here. See HTML export for this file:
https://mmaulwurff.github.io/doom-toolbox/documentation/OrgCheatSheet.html

Paragraphs are separated by an empty line. Links: [[https://orgmode.org/quickstart.html][Org mode quickstart]]. Formatting:
*bold* _underlined_ ~monospace~ +strikethrough+ /italics/ */_+combined+_/*.

Unordered lists:
- one
- two

Ordered lists:
1. one
2. two

Code block are between ~#+begin_src~ and ~#+end_src~. The code inside this block will
be put into ~main.c~ file when tangled.
#+begin_src c :tangle main.c
int main() { return 0; }
#+end_src

Macro. When exported or tangled, the following blocks are automatically put inside
this block:
#+begin_src c :noweb yes
// <<text-to-insert-here-name>>
#+end_src

#+begin_src c :exports none :noweb-ref text-to-insert-here-name
SPDX-FileCopyrightText: © 2026 Alexander Kromm <mmaulwurff@gmail.com>
#+end_src

#+begin_src c :exports none :noweb-ref text-to-insert-here-name
SPDX-License-Identifier: CC0-1.0
#+end_src

* Heading
** Second level heading
*** Third level heading

-----
This block puts this .org file into the exported HTML page verbatim for comparison.
#+begin_src elisp :exports both
(buffer-string)
#+end_src
