# SPDX-FileCopyrightText: © 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

#+title: Why GPLv3?

* Why not MIT?

First, GZDoom code, including ZScript, is GPLv3, and I'm not sure if it's legal to
use ZScript APIs in a non-GPLv3-compatible software.

Second, personal preference. I don't like that this code is included in other code,
which cannot be brought back.

* Why GPLv3-only?

Why not GPLv3-or-later?

I'm afraid that the next GPL versions can lose some restrictions.

#+begin_quote
The Free Software Foundation may publish revised and/or new versions of the GNU
General Public License from time to time. Such new versions will be similar in spirit
to the present version, but may differ in detail to address new problems or concerns.
#+end_quote

"Similar in spirit". Who decides what this "similarity" means? FSF? A judge? LGPL can
be considered "similar" in spirit. What if GPLv4 will be just LGPL?

My reasoning is that the value of software licensed under GPLv3 grows. And in
business world, everything has a price. So, when a big enough company decides that
it's cheaper to have less restrictive GPLv4 than to develop an alternative to a piece
of software licensed under GPLv3-or-later, then this company will make FSF make such
license. I think that there are ways to accomplish this. For example, exceptions can
be added to GPL if the end product is "for a good cause". Or if the company make a
generous donation to the open source community.

So, this project is GPLv3-only.
