# SPDX-FileCopyrightText: © 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# GitHub Action for dev builds
# https://docs.github.com/en/actions

name: dev-builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we want
# to allow these production deployments to complete.
concurrency:
  group: 'dev-build'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      uzdoom-version: '4.14.3'
    steps:
      - name: Check out
        uses: actions/checkout@v6

      # TODO: when Ubuntu 26.04 is available as GitHub runner, install Emacs with apt.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2t64 libpulse0
          sudo snap install emacs --classic

      - name: Cache UZDoom
        id: cache-uzdoom
        uses: actions/cache@v5
        with:
          path: ~/UZDoom.AppImage
          key: ${{ runner.os }}-uzdoom-v${{ env.uzdoom-version }}

      - if: ${{ steps.cache-uzdoom.outputs.cache-hit != 'true' }}
        name: Install UZDoom
        run: |
          wget -qO- https://github.com/UZDoom/UZDoom/releases/download/${{ env.uzdoom-version }}/Linux-UZDoom-${{ env.uzdoom-version }}.AppImage > ~/UZDoom.AppImage
          chmod +x ~/UZDoom.AppImage

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'tools/requirements-dev.txt'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements-dev.txt;

      - name: Check pre-commit hooks
        run: |
          pre-commit run -a

      - name: Test
        if: ${{ success() }}
        run: |
          xvfb-run --server-args "-screen 0 640x480x24" --auto-servernum scons TestAll

      - name: Check compatibility
        if: ${{ success() }}
        run: |
          xvfb-run --server-args "-screen 0 640x480x24" --auto-servernum scons CheckCompatibility

      - name: Build
        if: ${{ success() }}
        run: |
          scons Pk3All

      - name: Upload distributions
        if: ${{ success() }}
        uses: actions/upload-artifact@v6
        with:
          name: doom-toolbox
          path: |
            build/*.pk3
            !build/Typist.pk3

      - name: Clean up build
        if: ${{ success() }}
        run: |
          rm -r build

      - name: Export to HTML
        if: ${{ success() }}
        run: |
          scons HtmlAll

      - name: Configure pages
        if: ${{ success() }}
        uses: actions/configure-pages@v5

      - name: Upload pages
        if: ${{ success() }}
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy pages to GitHub Pages
        if: ${{ success() }}
        id: deployment
        uses: actions/deploy-pages@v4

  build_windows:
    runs-on: windows-2022
    # TODO: use common version for Linux and Windows?
    env:
      uzdoom-version: '4.14.3'
    steps:
      - name: Check out
        uses: actions/checkout@v6

        # TODO: cache choco?
      - name: Install system dependencies
        run: |
          choco install emacs

      - name: Cache UZDoom
        id: cache-uzdoom
        uses: actions/cache@v5
        with:
          path: ${GITHUB_WORKSPACE}/UZDoom
          key: ${{ runner.os }}-uzdoom-v${{ env.uzdoom-version }}

      - if: ${{ steps.cache-uzdoom.outputs.cache-hit != 'true' }}
        name: Install UZDoom
        shell: bash
        run: |
          wget -qO- https://github.com/UZDoom/UZDoom/releases/download/${{ env.uzdoom-version }}/Windows-UZDoom-${{ env.uzdoom-version }}.zip > UZDoom.zip
          unzip UZDoom.zip -d UZDoom
          PATH=$PATH:${GITHUB_WORKSPACE}/UZDoom

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'tools/requirements-dev.txt'

      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements-dev.txt;

      - name: Check pre-commit hooks
        shell: bash
        run: |
          pre-commit run -a

      - name: Test
        shell: bash
        if: ${{ success() }}
        run: |
          scons TestAll

      - name: Check compatibility
        shell: bash
        if: ${{ success() }}
        run: |
          scons CheckCompatibility
